# Generated by Django 2.2.4 on 2019-08-23 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='pub_dat',
            new_name='pub_date',
        ),
    ]
